### ISSUE TITLE
Request: How best to add day-night toggle

### ISSUE THREAD

**Issue by akbir** [siegerts/hugo-theme-basic#12]
Hi @siegerts - thank you for the awesome theme!

I was wondering how easy / hard it would be to extend the theme to support a day-night toggle (e.g two CSS files).

Keen for guidance / happy to help implement

**Comment by siegerts** [comment]
Hi @akbir! It's definitely possible to add with some JavaScript and add swap/add the style classes for a dark theme. The toggle selection can be stored in localStorage and then checked on page load. The lightweight option would be to use plain JS but you could also include a framework (React, Vue, etc) if you want more components or interactivity down the line.
