### ISSUE TITLE
Update exampleSite config with correct baseURL format

### ISSUE THREAD

**Issue by dtcrout** [siegerts/hugo-theme-basic#5]
The syntax highlighting is different when running the site in debug mode vs building it.

When running in debug mode, I see:
<img width="931" alt="Screen Shot 2019-06-03 at 9 23 59 PM" src="https://user-images.githubusercontent.com/22284211/58844632-159db300-8646-11e9-8f5a-1a9f824d4da4.png">

When building the site and viewing the generated html, I see:
<img width="931" alt="Screen Shot 2019-06-03 at 9 24 21 PM" src="https://user-images.githubusercontent.com/22284211/58844644-22220b80-8646-11e9-8408-9f75a43f6325.png">

**Comment by siegerts** [comment]
Hi @dtcrout! 

Is the build being served or just view as a static file? You'll need a server for the _highlight.js_ to load and run.  That's what handles the syntax highlight for code snippets.

I tested with `hugo serve` and `hugo serve --debug` and I see the expected output.

**Comment by dtcrout** [comment]
@siegerts , the contents of the generated `public` folder is being served via GitHub Pages and that's where I'm seeing the syntax highlighting not working.

**Comment by siegerts** [comment]
Hey!

I looked through your build and it looks like one of the stylesheets (`style.css`) is timing out, causing the highlight portion to not run.

Add a trailing `/` to the `baseURL` var in your config.toml file. Hopefully that will load the asset from the right path.

I'll update the config in the exampleSite.

**Comment by dtcrout** [comment]
Thanks @siegerts , that seemed to solve the issue!
